FROM alpine

RUN apk add --update --no-cache python3
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools

COPY . /

RUN pip3 install -r requirements.txt

EXPOSE 8000
ENTRYPOINT cd /wiki/ && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000 
